# Generated by Django 6.0.3 on 2026-03-04 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='客户名称')),
                ('credit_code', models.CharField(max_length=18, unique=True, verbose_name='统一社会信用代码/身份证号')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='LeaseContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(max_length=50, unique=True, verbose_name='合同编号')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='合同总金额')),
                ('start_date', models.DateField(verbose_name='起租日期')),
                ('end_date', models.DateField(verbose_name='到期日期')),
                ('status', models.CharField(choices=[('ACTIVE', '生效中'), ('SETTLED', '已结清'), ('DEFAULT', '违约')], default='ACTIVE', max_length=20, verbose_name='合同状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='leasing_business.customer', verbose_name='关联客户')),
            ],
        ),
        migrations.CreateModel(
            name='LeasedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=100, verbose_name='租赁物名称')),
                ('asset_sn', models.CharField(max_length=100, unique=True, verbose_name='设备识别码/车架号')),
                ('initial_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='初始采购/评估价值')),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='当前重估价值')),
                ('physical_status', models.CharField(choices=[('IN_USE', '使用中'), ('MAINTENANCE', '维修中'), ('DISPOSED', '已处置')], default='IN_USE', max_length=20, verbose_name='物理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入账时间')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='leasing_business.leasecontract', verbose_name='所属合同')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(verbose_name='巡检日期')),
                ('inspector', models.CharField(max_length=50, verbose_name='巡检人员')),
                ('revalued_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='本次巡检估值')),
                ('risk_level', models.CharField(choices=[('GREEN', '绿灯 - 正常'), ('YELLOW', '黄灯 - 需关注'), ('RED', '红灯 - 风险警报')], default='GREEN', max_length=10, verbose_name='风险预警灯号')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='巡检备注/风险描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_logs', to='leasing_business.leasedasset', verbose_name='关联租赁物')),
            ],
        ),
    ]
